version: ~> 1.0

os: linux
dist: bionic
language: java

git:
  depth: 10
  quiet: true

branches:
  only:
  - next
  - gradle-6.5

env:
  global:
    - AWS_ACCESS_KEY_ID="AKIAJQUIQIL3XTBHT3DA"
    - secure: "C5Y0miWN35KMpWNT/r3n31J/JjUJA6a9I/w5DUkm5xFLv1oStOvNL9KykRQIL4+9yW7hYUcGOI0iP9ZjtbxRouP5//PCjhlgzIGJ3WImVZq4fLNl3sq3DYtgZJT5rUeXn8r8cKE3/sloEbcbz7dFNXmbSACuaZ0/T3IZpgP/Yrs="

before_cache:
  - rm -f  $HOME/.gradle/caches/*/*.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
  - rm -rf $HOME/.gradle/caches/*/fileHashes/
  - rm -rf $HOME/.gradle/caches/*/scripts*/

cache:
  directories:
    - $HOME/.sonar
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install:
  - echo -e "org.gradle.internal.launcher.welcomeMessageEnabled=false" >>gradle.properties
  - echo -e "org.gradle.dependency.verification=lenient"               >>gradle.properties
  - echo -e "org.gradle.caching=false"                                 >>gradle.properties

before_script:
  - ./gradlew -v

script:
  - ./gradlew jar test #--info

jobs:
  include:
    - name: openjdk8
      jdk: openjdk8
    - name: openjdk11
      jdk: openjdk11
    - name: openjdk14
      jdk: openjdk14

    - name: jdk8
      os: osx
      osx_image: xcode9.3
    - name: jdk13
      os: osx
      osx_image: xcode10.3
    - name: jdk14
      os: osx
      osx_image: xcode12

    - name: arm64
      arch: arm64
    - name: ppc64le
      arch: ppc64le
    - name: s390x
      arch: s390x

    # - name: 'Sonar'
    #   jdk: openjdk13
    #   script:
    #     - ./gradlew clean
    #     - ./gradlew test pmdMain pmdTest spotbugsMain spotbugsTest jacocoTestReport sonarqube


before_deploy:
  - pip install --user awscli
  - ./gradlew copyRuntimeLibs javadoc

deploy:
  - provider: script
    script: ~/.local/bin/aws s3 sync --region=us-east-1 --cache-control "public, max-age=86400" --content-encoding utf-8 --delete build/docs/javadoc/ s3://website-javadoc.freenetproject.org
    on:
      branch: next
      jdk: openjdk8
  - provider: script
    script: ./gradlew -x test publish
    on:
      tags: true
      jdk: openjdk8
  - provider: releases
    token:
      - secure: CDYRFrmkAOdn4QJVww6/pziDVdZ67fvRsLOKbilao/oRdP0uvsYS+OfX+Spu/Y0qCY0xSehvqgUoD8KoFqWuhos3iF4N515S5WNuiqOao7Ac2vBCt0ZMJy7MktyE5mYOD1Paf891n6Z+eILWGI54GGEau3JPes0G9jdMphW4ma8=
    prerelease: true
    file: build/output/*jar
    file_glob: true
    on:
      tags: true
      jdk: openjdk8
