name: Build

on: [push, pull_request]

jobs:
  validation:
    name: "Wrapper Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1

  build:
    needs: [validation]
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        java: [8, 11, 14]

    env:
      GITHUB_CI: true
      GRADLE_OPTS: -Dorg.gradle.caching=false -Dorg.gradle.daemon=false

    name: Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:

      - name: Checkout
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          architecture: x64

      - name: Build Jar
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: jar

      - name: Unit Tests
        if: ${{ success() }}
        uses: eskatos/gradle-command-action@v1
        with:
          dependencies-cache-enabled: true
          arguments: test
